#!/usr/bin/env python

# MSVC-6.0 chokes on code generated by the Meta-Object-Compiler (moc) included
# in QtWin230-NonCommercial.exe.  This program patches the output of moc.

import os

os.chdir('Qwt3D')

for source, bad, good in (
    ('moc_qwt3d_plot.cpp',
     '#include "qwt3d_plot.h"',
     os.linesep.join(['#include <qgl.h>', '#include "qwt3d_plot.h"'])
     ),
    ('moc_qwt3d_surfaceplot.cpp',
     'Qwt3D::Plot3D::className',
     'Plot3D::className'
     ),
    ):
    if os.path.exists(source):
        os.remove(source)
    os.system('nmake %s' % source)
    old = open(source, 'r').read()
    new = old.replace(bad, good)
    if new != old:
        open(source, 'w').write(new)
        
os.chdir(os.pardir)

# Local Variables: ***
# mode: python ***
# End: ***
